# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 02:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglikes',
            old_name='blog_comment_id',
            new_name='blog_like_id',
        ),
        migrations.RemoveField(
            model_name='bloglikes',
            name='blog_comment_content',
        ),
        migrations.RemoveField(
            model_name='bloglikes',
            name='blog_comment_name',
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 15, 2, 39, 56, 56375)),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 15, 2, 39, 56, 58898)),
        ),
        migrations.AlterField(
            model_name='bloglikes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 15, 2, 39, 56, 61079)),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 15, 2, 39, 56, 53869)),
        ),
    ]
