# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerapp', '0002_auto_20160715_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 15, 9, 6, 48, 711866)),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 15, 9, 6, 48, 714337)),
        ),
        migrations.AlterField(
            model_name='bloglikes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 15, 9, 6, 48, 716414)),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 15, 9, 6, 48, 709470)),
        ),
        migrations.AlterUniqueTogether(
            name='bloglikes',
            unique_together=set([('blog_id', 'blog_like_owner')]),
        ),
    ]
